spring:
  application:
    name: SystemPay
  datasource:
    url: jdbc:postgresql://localhost:5432/systempay
    username: postgres
    driver-class-name: org.postgresql.Driver
    password: JARgal2005
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
