spring:
  application:
    name: SystemPay
  datasource:
    url: jdbc:postgresql://localhost:5432/systempay
    username: postgres
    driver-class-name: org.postgresql.Driver
    password: JARgal2005
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      backs: all
#      retries: 3
#      enable-idempotence: true
#    consumer:
#      group:
#        id: CountryCounter
